In [56]:
import numpy as np
import pandas as pd
from pandas import Series, 
#https://www.machinelearningplus.com/python/101-numpy-exercises-python/

In [35]:
#1
arr_0 = np.array([0,1,2,3,4,5,6,7,8,9])
arr_0

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
#2
df_0 = np.full((3,3), True, dtype=bool)
df_0

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [34]:
#3
df_1 = np.ones((3,3), dtype=bool)
df_1

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [39]:
#4
#  4 % 2 will result in a 0. Four divided by two results in a 2 with a remainder of 0.
5 % 2 will result on a 1. Five divided by two results in a 2 with a remainder of 1.
arr_1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr_1 = arr[arr % 2 == 1]
arr_1
#odd numbers

array([1, 3, 5, 7, 9])

In [41]:
#5
arr_1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr_1 = arr[arr % 2 == 0]
arr_1
#even numbers

array([0, 2, 4, 6, 8])

In [46]:
arr_2 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr_2 = arr[arr % 2 == 1] = -1
arr_2
#odd numbers

-1

In [49]:
#6
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]) #np.arange(10)
out = np.where(arr % 2 == 1, -1, arr)
print(arr)
out

[0 1 2 3 4 5 6 7 8 9]


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [67]:
#7
array_8 = np.arange(10)
array_8.reshape(2,-1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [66]:
#8
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.concatenate([a,b], axis=0)
np.vstack([a, b])
np.r_[a, b]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [61]:
#9 How to stack two arrays horizontally?
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

np.concatenate([a, b], axis=1)
np.hstack([a, b])
np.c_[a, b]

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [65]:
#10. How to generate custom sequences in numpy without hardcoding?

a = np.array([1,2,3])
np.r_[np.repeat(a, 3), np.tile(a, 3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [68]:
#11  How to get the common items between two python numpy arrays?

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

In [69]:
#12 How to remove from one array those items that exist in another?

a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
# From 'a' remove all of 'b'
np.setdiff1d(a,b)

array([1, 2, 3, 4])

In [70]:
#13 How to get the positions where elements of two arrays match?

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a == b)

(array([1, 3, 5, 7], dtype=int64),)

In [73]:
#14. How to extract all numbers between a given range from a numpy array?
a = np.array([2, 6, 1, 9, 10, 3, 27])
index = np.where((a >= 5) & (a <= 10))
a[index]

index = np.where(np.logical_and(a>=5, a<=10))
a[index]

a[(a >= 5) & (a <= 10)]

array([ 6,  9, 10])

In [ ]:
#15. How to make a python function that handles scalars to work on numpy arrays?

def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

maxx(1, 5)

In [78]:
#16. How to swap two columns in a 2d numpy array?

arr = np.arange(9).reshape(3,3)
arr[[1,0,2], :]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [77]:
arr[[0,1,2], :]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [82]:
#18. How to reverse the rows of a 2D array?

arr = np.arange(9).reshape(3,3)
arr[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [83]:
#19. How to reverse the columns of a 2D array?

arr = np.arange(9).reshape(3,3)
arr[:, ::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [84]:
#20. How to create a 2D array containing random floats between 5 and 10?

arr = np.arange(9).reshape(3,3)
and_arr = np.random.randint(low=5, high=10, size=(5,3)) + np.random.random((5,3))
rand_arr = np.random.uniform(5,10, size=(5,3))
print(rand_arr)

[[5.74892955 9.72396303 9.50398312]
 [5.73509664 5.481856   9.47428865]
 [7.04053375 5.26306014 6.84811438]
 [5.52396673 8.37546    8.31472829]
 [5.12273269 7.55305384 8.78235942]]


In [85]:
#21. How to print only 3 decimal places in python numpy array?

rand_arr = np.random.random((5,3))
np.set_printoptions(precision=3)
rand_arr[:4]
# word[0:2]  # characters from position 0 (included) to 2 (excluded) 'Py'

array([[0.325, 0.337, 0.155],
       [0.955, 0.738, 0.86 ],
       [0.259, 0.386, 0.737],
       [0.287, 0.865, 0.462]])

In [86]:
#22. How to pretty print a numpy array by suppressing the scientific notation (like 1e10)?

np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
rand_arr

array([[5.434e-04, 2.784e-04, 4.245e-04],
       [8.448e-04, 4.719e-06, 1.216e-04],
       [6.707e-04, 8.259e-04, 1.367e-04]])

In [88]:
#23. How to limit the number of items printed in output of numpy array?

a = np.arange(15)
np.set_printoptions(threshold=6)
a

array([ 0,  1,  2, ..., 12, 13, 14])

In [98]:
#24. How to print the full numpy array without truncating

a = np.arange(15)
np.set_printoptions(threshold=6)

#np.set_printoptions(threshold=np.nan)
#array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [99]:
#25. How to import a dataset with numbers and texts keeping the text intact in python numpy?

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
iris[:3]

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa']], dtype=object)

In [100]:
#26. How to extract a particular column from 1D array of tuples?

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)

species = np.array([row[4] for row in iris_1d])
species[:5]

C:\Users\Yuan\anaconda3\lib\site-packages\ipykernel_launcher.py:4: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  after removing the cwd from sys.path.


array([b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa'], dtype='|S18')

In [ ]:
#27. How to convert a 1d array of tuples to a 2d numpy array?

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)

iris_2d = np.array([row.tolist()[:4] for row in iris_1d])
iris_2d[:4]

iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[:4]

In [103]:
#47. How to replace all values greater than a given value to a given cutoff?

np.set_printoptions(precision=2)
np.random.seed(100)
a = np.random.uniform(1,50, 20)

In [102]:
a

array([27.627, 14.64 , 21.801, ...,  9.425, 40.995, 14.43 ])

# year_options = []

In [7]:
df = pd.read_csv('gapminderDataFiveYear.csv')

In [8]:
df

country  year         pop continent  lifeExp   gdpPercap
0     Afghanistan  1952   8425333.0      Asia   28.801  779.445314
1     Afghanistan  1957   9240934.0      Asia   30.332  820.853030
2     Afghanistan  1962  10267083.0      Asia   31.997  853.100710
3     Afghanistan  1967  11537966.0      Asia   34.020  836.197138
4     Afghanistan  1972  13079460.0      Asia   36.088  739.981106
...           ...   ...         ...       ...      ...         ...
1699     Zimbabwe  1987   9216418.0    Africa   62.351  706.157306
1700     Zimbabwe  1992  10704340.0    Africa   60.377  693.420786
1701     Zimbabwe  1997  11404948.0    Africa   46.809  792.449960
1702     Zimbabwe  2002  11926563.0    Africa   39.989  672.038623
1703     Zimbabwe  2007  12311143.0    Africa   43.487  469.709298

[1704 rows x 6 columns]

In [9]:
df['year']

0       1952
1       1957
2       1962
3       1967
4       1972
        ... 
1699    1987
1700    1992
1701    1997
1702    2002
1703    2007
Name: year, Length: 1704, dtype: int64

In [16]:
year_options = []
for year in df['year'].unique():
    year_options.append({'label':str(year),'value':year})
    
#Basically you turned out the data on List
    
print(year_options)

[{'label': '1952', 'value': 1952}, {'label': '1957', 'value': 1957}, {'label': '1962', 'value': 1962}, {'label': '1967', 'value': 1967}, {'label': '1972', 'value': 1972}, {'label': '1977', 'value': 1977}, {'label': '1982', 'value': 1982}, {'label': '1987', 'value': 1987}, {'label': '1992', 'value': 1992}, {'label': '1997', 'value': 1997}, {'label': '2002', 'value': 2002}, {'label': '2007', 'value': 2007}]


In [17]:
df_0 = pd.DataFrame(year_options)

In [18]:
df_0

label  value
0   1952   1952
1   1957   1957
2   1962   1962
3   1967   1967
4   1972   1972
5   1977   1977
6   1982   1982
7   1987   1987
8   1992   1992
9   1997   1997
10  2002   2002
11  2007   2007

# ---------------------------------------------------------------------------------------------------------------

In [21]:
import plotly.graph_objs as go
import pandas as pd


In [23]:
def update_figure(selected_year):
    filtered_df = df[df['year'] == selected_year]

    
    traces = []
    for continent_name in filtered_df['continent'].unique():
        df_by_continent = filtered_df[filtered_df['continent'] == continent_name]
        
        
        traces.append(go.Scatter(
            x=df_by_continent['gdpPercap'],
            y=df_by_continent['lifeExp'],
            text=df_by_continent['country'],
            mode='markers',
            opacity=0.7,
            marker={'size': 15},
            name=continent_name
        ))

In [24]:
print(traces)

NameError: name 'traces' is not defined