# Numpy

In [3]:
import numpy as np
import pandas as pd

In [2]:
from IPython.display import Image
from IPython.core.display import HTML 

In [4]:
# List of lists

data = [['tom',10], ['nick',15],['juli',14]]

df = pd.DataFrame(data)

df

0   1
0   tom  10
1  nick  15
2  juli  14

In [5]:
# From dict of narray/lists

data = {'name':['tom','zhang'],'age':[12,43]}

df = pd.DataFrame(data, index=['rank1','rank2'] , columns = ['name','age'])

df

# my favourite!!!!

name  age
rank1    tom   12
rank2  zhang   43

In [6]:
# DataFrame by passing lists of dictionaries and row indexes

data = [{'b': 2, 'c':3}, {'a': 10, 'b': 20, 'c': 30}]

df = pd.DataFrame(data, index =['first', 'second']) 
  
df

b   c     a
first    2   3   NaN
second  20  30  10.0

In [8]:
# Creating DataFrame using zip() function

# List1  
Name = ['tom', 'krish', 'nick', 'juli']  
    
# List2  
Age = [25, 30, 26, 22]  


list_of_tuples = list(zip(Name,Age))

list_of_tuples

df = pd.DataFrame(list_of_tuples, columns = ['Name','Age'])

df

Name  Age
0    tom   25
1  krish   30
2   nick   26
3   juli   22

In [ ]:
https://www.geeksforgeeks.org/different-ways-to-create-pandas-dataframe/#:~:text=%23%20print%20dataframe.&text=To%20create%20DataFrame%20from%20dict,n%20is%20the%20array%20length.

# --------------------------------------------------------------------

In [4]:
array = np.arange(20)

In [15]:
array.shape

(20,)

In [10]:
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [11]:
array_data_frame

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-17-19c6cc380bcd> in <module>
----> 1 array_data_frame

NameError: name 'array_data_frame' is not defined

SyntaxError: invalid syntax (<ipython-input-11-ce3df3bd8d70>, line 3)

# --------------------------------------------------------------------

In [5]:
arr = np.array([[1,2,3],[4,2,5]])

In [19]:
arr

array([[1, 2, 3],
       [4, 2, 5]])

In [17]:
type(arr)

numpy.ndarray

In [6]:
arr.dtype

dtype('int32')

In [18]:
arr.shape

(2, 3)

In [20]:
arr.size

6

In [21]:
arr.ndim

2

In [6]:
Image(url= "http://www.w3resource.com/w3r_images/python-data-type-list-excercise-13.svg", width=300, height=300)

In [7]:
a = np.array((1,3,2))

In [8]:
a

array([1, 3, 2])

In [9]:
a.ndim

1

# Lists

In [2]:
A = [1,2,3]

In [4]:
A

[1, 2, 3]

In [3]:
B = np.array(A)

In [5]:
B

array([1, 2, 3])

In [6]:
C = np.array([1,2,3])

In [7]:
C

array([1, 2, 3])

In [11]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [13]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [14]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [ ]:
#Using () creates a tuple which is basically an immutable list, 
#meaning once it is created you cannot add, change, or remove elements from the tuple.

#Using [] creates a list which works like an array or vector from other languages. 
#Elements can be added, removed, and changed

#array=matriz

A = {'to:2','would:5','Clap:4'} #dictionary
B = [1,3,4,5]
C = (6,7,8,9) #Tuples

In [ ]:
import numpy as np
import pandas as pd
list('zhang')
letters = list('name')
letters[0]
  mylist = [1,2,3,4,5]
for item in mylist:
    print(item)

In [15]:
a = np.arange(0, 10)

In [16]:
b = np.arange(0, 10, 2) #(start =, stop =, num=)

In [17]:
b

array([0, 2, 4, 6, 8])

In [22]:
D = np.arange(15).reshape(3,5)

In [18]:
D

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [24]:
E = np.arange(15).reshape(3,5,-1)

In [25]:
E

array([[[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4]],

       [[ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9]],

       [[10],
        [11],
        [12],
        [13],
        [14]]])

In [ ]:
#numpy.array(object, dtype = None, copy = True, order = None, subok = False, ndmin = 0)

In [53]:
F = np.array([1,2,3,4,5], ndmin = 3)

In [42]:
F

array([[[1, 2, 3, 4, 5]]])

In [38]:
G = np.array([1,2,3], dtype = complex)

In [36]:
G

array([1.+0.j, 2.+0.j, 3.+0.j])

In [39]:
H = np.array([1,2,3], dtype = object)

In [40]:
H

array([1, 2, 3], dtype=object)

In [44]:
I = np.array([[1,2,3],[4,5,6]])

In [45]:
I

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
print (I.shape)

(2, 3)


In [48]:
L = I.reshape(3,2)

In [49]:
L

array([[1, 2],
       [3, 4],
       [5, 6]])

In [56]:
numpy.empty(shape, dtype = float, order = 'C')

NameError: name 'numpy' is not defined

In [57]:
x = np.empty([3,2], dtype = int)

In [60]:
x

array([[         0, 1072693248],
       [         0, 1073741824],
       [         0, 1074266112]])

# Convert list to ndarray

In [64]:
y = [1,2,3]
M = np.asarray(y)

In [65]:
M

array([1, 2, 3])

In [70]:
M.dtype

dtype('int32')

In [71]:
s = 'Hello World'
a = np.frombuffer(s, dtype ='S1')

TypeError: a bytes-like object is required, not 'str'

# [:]

In [34]:
arr = np.arange(50)

In [38]:
arr2 = arr[:3]

[:3] it`s means start at 0 but 3 doesn`t get into it, ex:array([0, 1, 2])

In [47]:
b = np.arange(1,26)

In [48]:
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [49]:
b = np.arange(1,26).reshape(5,5)

In [50]:
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [56]:
b[2:,2:]

array([[13, 14, 15],
       [18, 19, 20],
       [23, 24, 25]])

[2:,2:] it`s means start at third rown uncounting second row and starting at the third number

TypeError: 'builtin_function_or_method' object is not subscriptable

In my case, it was occurred due to bad indentation.

Just indenting the line of code solved the issue

In [1]:
NUMPY

np.arange(0, 10)
ANSWER:array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])


np.arange(0, 10, 2)
ANSWER:np.array([0, 2, 4, 6, 8, 10])


np.linspace(0, 1000, 3)
ANSWER: array([0., 500., 1000.])

np.linspace(0, 5, 11) --> linspace is a code that it introduces the sequence of number that i want it, for instance, still being matriz
linspace(start =, stop =, num=)

--------------------------------------------------------------------------------------------------------------------------------------------

np.zeros(3)
np.ones(3)
np.eye(4) --> matriz identidade
I will get a matriz with numbers 0


I REALLY DON`T KNOW THE PURPOSE FOR THOSE CODE.


arr = np.zeros((5,5))
I will get a matriz (5x5) with numers 0

-----------------------------------------------------------------------------------------------------

np.random.rand(5) --> when you write it will show you fiver random number
np.random.rand(5)
np.random.rand(5) * 100

-----------------------------------------------------------------------------------------------------------------------

np.random.randint(0, 100, 10) --> it will give 10 random numbers between 0 and 100 ===> it`s like LINSPACE

-------------------------------------------------------------------------------------------------

np.around(1.23456789)
ANSWER:1.0

np.around(1.23456789, 2)
ANSWER:1.23

--------------------------------------------------------------------------------------------------------------

arr = np.random.rand(25)
arr.reshape((5,5)) --> whe use reshape we want it to change somenthing else.

-------------------------------------------------------------------------------------------------------------
MATHEMATICS METHODS

arr.max()
arr.min()
arr.argmax()
arr.argmin()

---------------------------------------------------------------------------------------------------------------

arr = np.arange(0, 30, 3)
ANSWER:array([0, 3, 6, 9, 12, 15, 18, 21, 24, 27)]


arr[3]   ==> [] giving you the number that i you wanna it
ANSWER:9

arr[2:5]  ===> that`s will give you in the a number range,whereas (however) the number 5 is going to include.
array[(6, 9, 12)]

arr[:5]
arr[2:]

arr[2:] = 100  ???????????????

--------------------------------------------------------------------------------------------------------------------

arr = np.arange(50).reshape((5, 10))
arr.shape
arr2 = arr[:3]

arr2[:] = 100 ???????????????????????

arr2 = arr[:3].copy  ????????????????????????????????????????????

---------------------------------------------------------------------------------------

# ??????
In [58]: arr
Out[58]: array([989,   2,   3,   4,   5])

# ???????????, ??? copy()
In [59]: arr2 = arr[:3].copy()

In [60]: arr2
Out[60]: array([989,   2,   3])

--------------------------------------------------------------------------------------------

arr2 = arr.[1:4,5:] ??????????????????????????????????????????????????????????

-----------------------------------------------------------------------

arr > 50
bol = arr > 50
arr[bol]

for example

array = np.linspace(0, 100, 30)
array.shape
array = array.reshape(3, 10)
array

array[0:2, 2]

-------------------------------------

numpy operation

arr = np.arange(0, 16)
arr
arr + arr or arr - arr
arr / arr or arr ** arr
arr + 100 or arr - 100

np.sqrt(arr)
np.exp
np.mean
np.std
np.sin
np.max
np.min

scipy.org

--------------------------------------------------------------------------------------------------------------------







Pandas

import numpy as np
import pandas as pd

labels = ['a', 'b', 'c']

minha_lista = [10, 20, 30]
arr = np.array([10, 20, 30])
--------------------------------------------------------------------------------------------------------------------

d = {'a':10, 'b':20, 'c':30}

Mix datas
------------------------------------------------------------------------------------------------------------------

minha_lista = [1, 2, 3]
Answer: [1, 2, 3]


np.array(minha_lista) --> array is code to turn your sequences at a matriz
array([[1, 2, 3,]]}  ==> 1 linhas x 2

-------------------------------------------------------------------------------------------------------------

pd.Series(data=minha_lista, index=labels)
Answer: a 10
        b 20
        c 30		
        dtype: int64

-------------------------------------------------------------------------------------------------------------------

series = pd.Series(data=minha_lista, index=labels)
series['b']
Answer: 20

--------------------------------------------------------------------------------------------------------------------

I HAVE TO DEFINE 'arr' FIRSTLY!!
pd.Series(arr, labels)
Answer: a 10
        b 20
        c 30		
        dtype: int64

-----------------------------------------------------------------------------------------------------------------

ser1 = pd.Series([1, 2, 3, 4],index=['EUA', 'Alemanha', 'URSS', 'Japao'])

ser2 = pd.Series([1, 2, 3, 4], index=['Alemanha', 'EUA', 'Italia', 'Japao'])

ser1 + ser2

NaN

-------------------------------------------------------------------------------------------------------------------

import pandas as pd
import numpy as np

np.random.seed(101)    ?????????????????????????????????


df = pd.DataFrame(randn[5, 4], index= 'A B C D E'. split(), columns='W X Y Z'.split())
df

df[`w`]
type(df[`w`])

-----------------------

df[['W', 'Z']]
Answer: you will get 2 chart

-----------------------

df['new'] = df['W'], df['X']
df

------------------------------

df.drop['new', axis=1]

---------------------------------

df.drop('new', axis=1, inplace=True)

--------------------------------

df.loc['A']

----------------------------------

df.loc[['A', 'B'], ['X', 'Y', 'Z']]

----------------------------------------

df.iloc[1:4, 2:]


---------------------------------------------------------------------------
SELECAO CONDICIONAL, SET_INDEX

import pandas as pd
import numpy as np

from numpy.random import random

np.random.seed(101) ????????????????????????? the same numbers

df = pd.DataFrame(np.random.randn(5,4), index='A B C D E'.split(), columns='W X Y Z'.split())

df > 0 
Answer: True or False (booleano number)

-------------------------------------------------------------------------------------------------------------------

bol = df > 0
df[bol]


df[['W', 'Z']]

df['W'] or df.W

---------------------------------------------------------------------------------------------------------------------

df['new'] = df['W'] + df['X']

df.drop('new', axis=1)
df.drop('new', axis=1, inplace=True)

--------------------------------------------------------------------------------------------------------------------

df.loc['A', 'W']  ===> to help you to find the exact data.

df.loc['A', 'B'], ['X', 'Y', 'Z']

df.iloc[1:4, 2:]

-------------------------------------------------------------------------------------------------------------------

df[df['W']>0]

df[df['W']>0]['Y']  ===> 
bol = df['W']>0
df2 = df[bol]
df2['Y']


df[(df['W']>0) and(&) (df['Y']>1)]

--------------------------------------------------------------------------------------------------------------------

df
df.reset_index()
or
df.reset_index(inplace=True)


---------------------------------

col = 'RS RJ SP AM SC'.split()
df['Estado'] = col
df

----------------------------------------------------------------------------------------------------------





INDICES MULTINIVEIS

import numpy as np
import pandas as pd

outside = ['G1','G1','G1','G2','G2','G2']
inside = [1,2,3,1,2,3]

hier_index = list(zip(outside, inside))

hier_index = pd.MultiIndex.from_tuples(hier_index)  ====> Object created


df = pd.DataFrame(np.random.randn(6, 2), index=hier_index, columns=['A', 'B'])

hier_index

hier_index = pd.MultiIndex.from_tuples(hier_index)

df.index.names = ['Grupo', 'Numeros']

df.xs(1)

df.xs(1, level='Numero')


----------------------------------------------------------------------------------------------------------------

DADOS AUSENTES

import numpy as np
import pandas as pd

d = {'A':[1, 2, np.nan], 'B':[5, np.nan, np.nan], 'C':[1, 2, 3]} ===> dictionary!!!!
d

df = pd.DataFrame(d)

df.dropna ==> take out NaN datas

df.dropna(thresh=2)

df.fillna(value='Fill na')

df['A'].fillna(value=df['A'].mean())

df.fillna(method='ffill')


---------------------------------------------------------

Group By

import pandas as pd
data = {['Empresa':['GOOG','GOOG','MSFT','MSFT','FB','FB'], 'Nome':['Sam', 'Charlie','Amy', 'Vanessa', 'Carl', 'Sarah'], 'Venda':[200,120,340,124,243,350]}

df = pd.DataFrame(data)

group = df.groupby('Empresa')

group

group.sum()
group.mean()
group.describe()

-------------------------------------------------------------------------------------

CONCATENAR, JUNTAR E MESCLAR

import pandas as pd

df1 = pd.DataFrame({'A':['A0', 'A1', 'A2', 'A3'], 'B':['B0', 'B1', 'B2', 'B3'], 'C':['C0', 'C1', 'C2', 'C3'], 'D':['D0', 'D1', 'D2', 'D3']}, index=[0, 1, 2, 3])


df2 = pd.DataFrame({'A':['A0', 'A1', 'A2', 'A3'], 'B':['B0', 'B1', 'B2', 'B3'], 'C':['C0', 'C1', 'C2', 'C3'], 'D':['D0', 'D1', 'D2', 'D3']}, index=[0, 1, 2, 3])							


pd.concat([df1, df2])

pd.concat([df1, df2], axis=1)

pd.merge(esquerda, direita, how='inner', on='key')
or
pd.merge(esquerda, direita, on=['key1', 'key2'])

TRYING TO SEE THE EXAMPLES IN THE VIDEO AGAIN.
----------------------------------------------------------------

OPERACAOES

import pandas as pd
df = pd.DataFrame({'col1':[dsdada

df['col2'].unique()


import numpy as np
np.unique(df['col2'])

len(df['col2'])

df['col2'].nunique()

df['col2'].value_counts()

df[df['col1']>2] & ()]

-------------------------------------------------------------------------------------------------------


ENTRADA E SAIDA DE DADOS


import numpy as np
import pabdas as pd

df = pd.read_csv or html

df =pd.read_csv('exemplo', sep='')

df.to_csv("exemplo.csv", sep=';', decimal=',')   ===> save the filed

df = pd.read_excel("Exemplo_Excel.xlsx", sheetname='Sheet1')

df = pd.read_html('xxxxx')








----------------------------------------------------------------------------------------------

import matplotlib.pyplot as plt

%matplotlib inline --> the function to this code is improve the visualization

import numpy as np

x = np.linspace(0, 5, 11) --> linspace is a code that it introduces the sequence of number that i want it, for instance
linspace(start =, stop =, num=)

x = np.lispace(0, 5, 11)

x

y = x * x

----------------------------------------------------------------------------------------------------

#Funcional
plt.plot(x, y) --> Shifting the graphic plt.plot(x, y, color='r' or 'r--') --> this is come MatLab code
plt.xlabel('Eixo X')
plt.xlavel('Eixo Y')
plt.title('Titulo')

or

#Funcional
plt.plot(x, y)
plt.show()
plt.xlabel('Eixo X')
plt.xlavel('Eixo Y')
plt.title('Titulo')
--> We use this code, when we forget writting this code "%matplotlib inline"

--------------------------------------------------------------------------------------------

plt.subplots(nrows=1, ncols=2)

or

plt.subplot(1, 2, 1)
plt.plot(x, y, 'r--')
plt.subplot(1, 2, 1)
plt.plot(y, x, 'r--')



-------------------------------------------------------------------------------------------------------


Python Introduction

#message
# -*- coding: utf-8 -*-
print('Hello')

# print is commando when you wanna print some code

print(2 +,-,...)

Sintax

= operator atribuition
int
string ( tect)
bol (booleana) true or false
1.1 float

x = "string" text with "

if

x = 10
y = 20

if x < y:
print('vc esta cert')
else:
print( vc esta errado)



a = 7
b = 6

if b > a:
	if b > 0:
		print("b e maior do que a\nb e positivo")
	else:
		print("b nao e maior que a nem positivo")

else:
	print("b menor que a")

----------------------------------------------------------------

x = 1
y = 2

if x == y:
	print("numeros iguais")
elif y > x:
	print("x menor que y")
else:
	print("numero diferentes")

--------------------------------------------------------------------
loop

x = 1

while x < 10:
	print(x):
	x = x+1

--------------------------------------------------------------------
 LISTA (for)


list1 = [1, 2, 3, 4, 5, 6]
list2 = ["hello", "z", "ds"]

for i in list1:
	print(i)
1
2
3
4
5
6

or 

hello
z
ds


for i in range(10, 20, 2):
	print(i)

10
12
14
16
18

------------------------------------------------
INPUT

numero = input("Digite um numero:")
print("o numero digitado e:")
print(numero)

------------------------------------------------------------------------------
FUNCTION

def soma(x, y):
	print(x, y)

soma(2, 2)

----------------------------------------------------------------------------------
RETURN

def soma(x, y):
	return x+y

s = soma(2, 3):
print(s)

------------------------------------------------
CONCATENACAO

a = "zhang"
b = "yuan"

z = a + "" + b
print(z)


tamanho = len(concatenar)
print(tamanho)
Answer: it will give you the amount numbers that i you have.


a = "Diego"
b = "Mariana"

concatenar = a + " " + b

print(a[2])
print((a[2:]).lower()) --> minusculo	
print((a[2:]).upper()) --> maiusculo


strip
split

---------------------------------


{} servem para criar/referenciar objetos
[] servem para criar/referenciar arrays

data = pd.DataFrame(dic)
you write this code when you want to see the tables,

----------------------------------------------------------------


df = pd.read_html('https://www.fdic.gov/bank/individual/failed/banklist.html')
df
df = df[0]
data = pd.DataFrame(df)

data.set_index('City', inplace=True)



GitHub

import pandas as pd
import numpy as np


A = pd.DataFrame({'a':[4,5,6],'b':[8,6,4]}, index=[234,2352,1231])
test1 = pd.DataFrame([[4,7,8],[2,3,5],[6,8,12]], index=[234,423,123], columns=['a','d','s'])

test2 = pd.DataFrame({'a':[4, 5, 6],'b':[8, 6, 4],'c':[8, 6, 4]}, index=pd.MultiIndex.from_tuples([('d',1),('d',2),('s',4)], names=['d','x']))

df = pd.melt(A, id_vars=['a'], var_name='city', value_name='temperature')

df = pd.melt(A, id_vars=['a'], var_name='city', value_name='temperature')
df.set_index('a', inplace=True) 

df = pd.melt(test1)


A = pd.DataFrame({'a':[4,5,6],'b':[8,6,4],'c':[8,6,4]}, index=[77,88,99])

B = pd.DataFrame({'a':[4123,5123,6123],'b':[8231,6232,4123],'c':[8123,643,423]}, index=[11,44,33])

df = pd.concat([A, B], keys=['wagner', 'Luiz'])

df.loc['Luiz']
df = pd.concat([A, B], keys=['wagner', 'Luiz'], axis=1)




df.drop(['B', 'C'], axis=1)

df.drop(columns=['B', 'C']


My Job (my First Project)!!!


data.drop(data.index[0], inplace=True)








SyntaxError: invalid syntax (<ipython-input-1-8c3907d957a0>, line 14)

In [18]:
np.eye(3) #matriz identify

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
np.arange(0,101)/100

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
       0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21,
       0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32,
       0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43,
       0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54,
       0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65,
       0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76,
       0.77, 0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87,
       0.88, 0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98,
       0.99, 1.  ])

In [42]:
g = np.random.rand(25)

In [43]:
print ("\n", g)


 [0.75459102 0.14381742 0.95953353 0.36729533 0.80169177 0.87099375
 0.56635914 0.66663352 0.56521545 0.54928085 0.40947176 0.76716401
 0.73769485 0.73183304 0.13546818 0.39389467 0.01824635 0.33927861
 0.42756658 0.10580829 0.08220054 0.15580343 0.07749379 0.94174534
 0.43243546]


In [44]:
a = np.array([[1, 2, 4], [5, 8, 7]], dtype = 'float') 
print ("\n", a)


 [[1. 2. 4.]
 [5. 8. 7.]]


In [21]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [22]:
np.linspace(0,5,2)

array([0., 5.])

In [12]:
b = np.arange(1,26).reshape(5,5)

In [13]:
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [14]:
print(b.shape)

(5, 5)


In [15]:
print("Array Dimension = ",len(b.shape))

Array Dimension =  2


In [16]:
b[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [17]:
b[3:,1:]

array([[17, 18, 19, 20],
       [22, 23, 24, 25]])

In [18]:
b[3:,2:]

array([[18, 19, 20],
       [23, 24, 25]])

In [19]:
b[1:5]

array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [20]:
b[0:5]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [22]:
b[3,4].shape

()

In [23]:
b[:3,1].shape

(3,)

In [24]:
b[:3,1:2]/shape

NameError: name 'shape' is not defined

In [ ]:
b[-1,:]

In [26]:
b[2:,1:]

IndexError: too many indices for array: array is 0-dimensional, but 2 were indexed

In [ ]:
y1 = infra['transm'].to_numpy()

In [ ]:
q = pd.to_numeric(i, errors='coerce')

In [ ]:
np.sum(mat)
mat.sum()
np.std(mat) #std -> desvio padrao
mat.sum(axis=0)
mat.sum(axis=1)
mat.sum(axis=0)